/*
SQLyog Ultimate v12.09 (32 bit)
MySQL - 10.3.22-MariaDB : Database - projetos
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`projetos` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `projetos`;

/*Table structure for table `PROJETOS` */

DROP TABLE IF EXISTS `PROJETOS`;

CREATE TABLE `PROJETOS` (
  `INT_PROJ` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `NM_PROJ` varchar(255) NOT NULL,
  `D_INI` date NOT NULL,
  `D_FIM` date NOT NULL,
  PRIMARY KEY (`INT_PROJ`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Data for the table `PROJETOS` */

insert  into `PROJETOS`(`INT_PROJ`,`NM_PROJ`,`D_INI`,`D_FIM`) values (2,'Novo projetison','2021-04-26','2021-04-30');

/*Table structure for table `PROJETO_TEM_ATIVIDADE` */

DROP TABLE IF EXISTS `PROJETO_TEM_ATIVIDADE`;

CREATE TABLE `PROJETO_TEM_ATIVIDADE` (
  `INT_PROJ_ATV` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `INT_PROJ` int(11) unsigned NOT NULL,
  `NM_ATVD` varchar(255) NOT NULL,
  `D_INI` date NOT NULL,
  `D_FIM` date NOT NULL,
  `LG_FIN` enum('S','N') DEFAULT 'N',
  PRIMARY KEY (`INT_PROJ_ATV`),
  KEY `PROJETO_TEM_ATIVIDADE_ibfk_1` (`INT_PROJ`),
  CONSTRAINT `PROJETO_TEM_ATIVIDADE_ibfk_1` FOREIGN KEY (`INT_PROJ`) REFERENCES `PROJETOS` (`INT_PROJ`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `PROJETO_TEM_ATIVIDADE` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
