
CREATE DATABASE /*IF NOT EXISTS*/`DB_DESAFIO` /*DEFAULT CHARACTER SET latin1 */;

USE `DB_DESAFIO`;

CREATE TABLE IF NOT EXISTS `PROJETOS` (
  `INT_PROJ` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `NM_PROJ` varchar(255) NOT NULL,
  `D_INI` date NOT NULL,
  `D_FIM` date NOT NULL,
  PRIMARY KEY (`INT_PROJ`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `PROJETO_TEM_ATIVIDADE` (
  `INT_PROJ_ATV` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `INT_PROJ` int(11) unsigned NOT NULL,
  `NM_ATVD` varchar(255) NOT NULL,
  `D_INI` date NOT NULL,
  `D_FIM` date NOT NULL,
  `LG_FIN` enum('S','N') DEFAULT 'N',
  PRIMARY KEY (`INT_PROJ_ATV`),
  KEY `PROJETO_TEM_ATIVIDADE_ibfk_1` (`INT_PROJ`),
  CONSTRAINT `PROJETO_TEM_ATIVIDADE_ibfk_1` FOREIGN KEY (`INT_PROJ`) REFERENCES `PROJETOS` (`INT_PROJ`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

